### ISSUE TITLE
Opening a new window doesn't hide the previous one when in solo/fullscreen mode

### ISSUE THREAD

**Issue by diogox** [salman-abedin/crystal#3]
As I mentioned in a previous issue, I noticed two things. This is the second.

I'm not entirely sure if this was on purpose, because you want to keep the script agnostic, but since there's already `bspc` calls right at the beginning of the script, I think the problem I mentioned in the title can be solved with some kind of `bspc subscribe`?

**Comment by diogox** [comment]
On this note, I don't believe it shows the previous window when you close the current one either :thinking: 

But I made some light modifications to the script (basically just renaming it, since crystal is a programming language's name), so I might have screwed up my version of the script :sweat_smile:

**Comment by salman-abedin** [comment]
The bspc calls are for bspwm users like myself and thanks to the way shellscripts work, they shouldn't cause you any trouble what so ever.

As for the previous window not being shown, keep in mind, **Crystal** will unhide only the windows from the current desktop.
In any case, this issues seems to be pointing at the fact that there is something wrong going on with **xdo**.
I'm gonna ask you to verify that you have **xdo** installed and properly working.

P.S.: Renaming the script wil not cause any problem (due to my generously written generic **Makefile**) other than me getting a little hurt. :p

**Comment by diogox** [comment]
Actually, I just checked my `sxhkd` configs and turns out I had to two hotkeys defined in different places, and when closing a window I was running `xdo close` instead of your script :sweat_smile: My bad

Regarding hiding the previous window when we open a new one and we're already in `solo` mode, I suppose that's not a `Crystal` feature atm?

**Comment by salman-abedin** [comment]
Well, I assume that would be a very complex for a noob like me.
But I will see if I can come up with something or not.
No promises though. =)
